const CHANGE_TAB = "CHANGE_TAB";
const UPD_USERS = "UPD_USERS";
const CHOOSE_USER = "CHOOSE_USER";
const UPD_POSTS = "UPD_POSTS";
const UPD_COMMENTS = "UPD_COMMENTS";
const UPD_TODOS = "UPD_TODOS";
const UPD_ALBUMS = "UPD_ALBUMS";
const UPD_PHOTOS = "UPD_PHOTOS";

 export { CHANGE_TAB, UPD_USERS, CHOOSE_USER, UPD_POSTS, UPD_COMMENTS, UPD_TODOS, UPD_ALBUMS, UPD_PHOTOS };